### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by joseluisvf** [joseluisvf/SEBC#2]
Issue created to monitor the progress of the gruesome installation process.

System configuration checks
- [X] Check vm.swappiness on all your nodes
- [X] Show the mount attributes of all volumes
- [X] Show the reserve space of any non-root, ext-based volumes
- [X] Disable transparent hugepage support
- [X] List your network interface configuration
- [X] List forward and reverse host lookups using getent or nslookup
- [X] Show the nscd service is running 
- [X] Show the ntpd service is running
- [X] Capture all of this work in labs/1_preinstall.md

MySQL 

- [X] configure mysql with a replica server
- [X] Download and implement the official MySQL repo
- [X] Start the mysqld service
- [X] run mysql_secure_installation
- [X] On the master MySQL node, grant replication privileges for your replica node
- [X] in a second terminal session, log into the MySQL master and show its status
- [X] login to the replica server and configure a connection to the master
- [X] initiate slave operations on the replica
- [X] once successful, capture the outputof the slave/master relationship and store it in labs/2_replica_working.md
- [X] install the connector

CM Install
- [X] install the Data Hub Edition
- [X] install CDH using parcels
- [X] deploy only the Coreset of CDH services
- [X] deploy three ZooKeeper instances
- [X] rename your cluster after your GitHub name
- [X] once you've renamed your cluster and it is healthy, take a screenshot of the home page and name the file labs/3_cm_installed.png
- [] mark your Issue 'submitted' unless you plan to complete the Bonus Lab

**Comment by joseluisvf** [comment]
The cluster is healthy, aside from the following warning:
```
    HDFS: Java Heap Size of NameNode in Bytes
    Java Heap Size of NameNode in Bytes is recommended to be at least 1GB for every million HDFS         blocks. Suggested minimum value: 4294967296
```
But this is, I believe, inevitable given the hardware specifications of the (cheap) instances.

**Comment by joseluisvf** [comment]
As regards the local parcel installation, we should take notice that 
```
https://ip-172-31-20-167.eu-west-1.compute.internal:80/cdh5.9
```
will not work. It should instead be
```
http://ip-172-31-20-167.eu-west-1.compute.internal:80/cdh5.9
```

Also, a cool fact about CM is that, as is made evident by the image, it will not allow us to install parcels not supported by its current version.

**Comment by mfernest** [comment]
Outstanding presentation in the notes. Top of class.
